---
os_firewall_allow:
- service: Kubernetes kubelet
  port: 10250/tcp
- service: http
  port: 80/tcp
- service: https
  port: 443/tcp
- service: OpenShift OVS sdn
  port: 4789/udp
  when: openshift.common.use_openshift_sdn | bool
- service: Calico BGP Port
  port: 179/tcp
  when: openshift.common.use_calico | bool

# oreg_url is defined by user input
oreg_host: "{{ oreg_url.split('/')[0] if (oreg_url is defined and '.' in oreg_url.split('/')[0]) else '' }}"
oreg_auth_credentials_path: "{{ openshift.common.data_dir }}/.docker"
oreg_auth_credentials_replace: False

l_bind_docker_reg_auth: False
